### ISSUE TITLE
你好有事找你

### ISSUE THREAD

**Issue by liuchaodev** [Sunnshino/colorUI-for-uniApp#1]
你好我之前写的一个开源类库，忘记删除账号密码，请将账号密码删除，避免引起不必要的麻烦，感谢配合，我的电话是18311200021，请看到与我联系

**Comment by Sunnshino** [comment]
你好，已经删除.

**Comment by szhlliuchao** [comment]
感谢！

**Comment by liuchaodev** [comment]
你好 我刚刚查看还是可以看到 在config.js中

**Comment by szhlliuchao** [comment]
components/ali-oos/config.js
pages/up-img/up-img.vue
components/sunui-upimg.vue
这三个未知，请删除

**Comment by Sunnshino** [comment]
刚才重新审查了一遍，均已修改.



------------------ Original ------------------

**Comment by szhlliuchao** [comment]
Sunnshino/sunUi-for-uniApp – sunui-upimg.vue
Sunnshino/sunUi-for-uniApp – up-img.vue
兄弟 这还有两处未删除部分

**Comment by liuchaodev** [comment]
删除完成加个微信好友18311200021 以后经常联系，有问题互相探讨，谢谢。

**Comment by ADDASH2016** [comment]
大佬 你发错人了吧 我都没有操作过啊


------------------ 原始邮件 ------------------
发件人: "szhlliuchao"<notifications@github.com>;
发送时间: 2019年5月21日(星期二) 中午11:19
收件人: "Sunnshino/sunUi-for-uniApp"<sunUi-for-uniApp@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [Sunnshino/sunUi-for-uniApp] 你好有事找你 (#1)




Sunnshino/sunUi-for-uniApp – sunui-upimg.vue
 Sunnshino/sunUi-for-uniApp – up-img.vue
 兄弟 这还有两处未删除部分

**Comment by ADDASH2016** [comment]
大哥 你是不是找错人啦




------------------ 原始邮件 ------------------
发件人: "szhlliuchao"<notifications@github.com>;
发送时间: 2019年5月21日(星期二) 中午11:20
收件人: "Sunnshino/sunUi-for-uniApp"<sunUi-for-uniApp@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [Sunnshino/sunUi-for-uniApp] 你好有事找你 (#1)




删除完成加个微信好友18311200021 以后经常联系，有问题互相探讨，谢谢。

**Comment by Sunnshino** [comment]
好了.



------------------ Original ------------------

**Comment by liuchaodev** [comment]
谢谢🙏
